### ISSUE TITLE
Door controls somewhat confusing on Nix

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#18] opened 2016-06-24 08:53 UTC
The system that controls whether a door is locked tells you "All doors have been unlocked", so when you find one that still won't open (controlled by another console) it's confusing.

Player only reacts the first time you try to open a locked door, can I get a "Locked! Need to find another console, dammit" reaction when you try a second locked door? Additionally, can there be a visual cue for if it's locked or not? Red instead of blue lights, maybe?

**Comment by Maxwolf** [comment] 2016-06-26 23:24
Yes, I will make the doors change colors based on current locked status that is a great idea. I will also change up the program that uses the door to show a picture or something like that of the door it is actually controlling I think that will make the system make more sense when you unlock a door it can show it changing color on the graphical interface so the player knows "Aha this door is open"

**Comment by kallman1206** [comment] 2016-06-27 02:28
I mean you have some kind of minimap if the teleporter and PDA is any indication, so could mark it on a copy of that when it opens them, if that's not tedious :P

**Comment by Maxwolf** [comment] 2016-06-27 02:46
Fox had a neat idea where we could make it so the terminals change a particular color of door. So the blue stripe could be different colors and have like Doom a blue door, red door, yellow door and then the console would be "Nix Yellow Doors" and when you unlock it all yellow doors on Nix will unlock.

I think that would make more sense? Then you could find a locked yellow door, and then roam around looking for a yellow console or something similar (maybe the text on the terminal is just yellow instead of the whole thing).

**Comment by kallman1206** [comment] 2016-06-27 02:51
I seem to recall you saying the "get blue key for blue door" seemed wonky and tired, but maybe you meant specifically in the "kill enemies until one drops it" vein. Not that there's any incentive not to murder every sons of a bitches you come across anyhow ;)

**Comment by Maxwolf** [comment] 2016-06-27 03:04
Yeah I am torn about what to do with it. The computer console thing was meant to be like our own twist on the concept of a keycard.

Yes I believe the concept of looking for a blue keycard to open a blue door is tired.

**Comment by kallman1206** [comment] 2016-06-27 03:44
It's cliche because it's so clear a design decision, I guess? Hard to get less ambiguous about what opens where. Compare Metal Gear for the NES, where you had a number of physical keys, and had to try each one until the door opened, on dozens of doors with no indication of which was correct. Hard to argue that that's better in any way, lol. Does make a conceit of it being a loss of immersion.... but if killing hundreds of mall cop dudes and a triangular eyeball cat has you feeling immersed that's another matter entirely.

**Comment by Maxwolf** [comment] 2016-06-27 20:29
Agree that is why it is cliche. The players can see through your game and the mechanic you chose, it has no relation to the area you are in. With Doom it was the whole "I just got a blue card last level" but Doomguy doesn't keep the blue card and has to re-get it every level and that is what particularly made it tired. That whole feeling of _"I already did this"_

With the computer terminals at least it feels more like you need to find that one particular console to let you progress through the level but I guess at the end of the day it's the same thing. The thing that makes ours different is the interaction with a terminal rather than picking something up.

**Comment by kallman1206** [comment] 2016-06-27 21:18
Consider letting us hack doors open,  nobody seems too concerned that the consoles are all left open as is, right? Maybe spawn guards at the skipped console tasked with hunting us down?

**Comment by Maxwolf** [comment] 2016-06-27 22:49
The reason for the consoles in the first place (and keycards in doom) is to force the player to goto other areas in the level they would not normally goto. Hacking the door would eliminate this need and make the game feel overall much shorter.

**Comment by Maxwolf** [comment] 2016-07-02 10:00
Ok made a keycard system with primary colored keycards so we have more than 3 and have things like purple, amber, and white doors + their keycards. I will re-work the logic in some levels so the computer consoles + keycards are used and not always the consoles.

Locked doors only prompt about keycard and door being locked a single time, however there is game info text that appears now that says "This door is opened elsewhere" or "This door required a keycard" so the player knows what must be done.

**Comment by Maxwolf** [comment] 2016-07-02 10:36
Cleaned up the consoles and added blue keycard door to Nix to mix things up. I will do more of this on the other maps but I can close this now as the issue is solved.

**Closed by Maxwolf** 2016-07-02 10:36 UTC
Labels: bug, enhancement
